//assets/images/leagueLogos.tsx
export const leagueLogos: Record<string, any> = {
  "ball_logo_mlb.png": require("./ball_logo_mlb.png"),
  "ball_logo_il.png": require("./ball_logo_il.png"),
  "ball_logo_pcl.png": require("./ball_logo_pcl.png"),
  "ball_logo_aapb.png": require("./ball_logo_aapb.png"),
  "ball_logo_abl.png": require("./ball_logo_abl.png"),
  "ball_logo_cal.png": require("./ball_logo_cal.png"),
  "ball_logo_cl.png": require("./ball_logo_cl.png"),
  "ball_logo_cpbl.png": require("./ball_logo_cpbl.png"),
  "ball_logo_dsl.png": require("./ball_logo_dsl.png"),
  "ball_logo_el.png": require("./ball_logo_el.png"),
  "ball_logo_fcl.png": require("./ball_logo_fcl.png"),
  "ball_logo_fl.png": require("./ball_logo_fl.png"),
  "ball_logo_fsl.png": require("./ball_logo_fsl.png"),
  "ball_logo_acl.png": require("./ball_logo_acl.png"),
  "ball_logo_alpb.png": require("./ball_logo_alpb.png"),
  "ball_logo_kbol.png": require("./ball_logo_kbol.png"),
  "ball_logo_lmb.png": require("./ball_logo_lmb.png"),
  "ball_logo_mwl.png": require("./ball_logo_mwl.png"),
  "ball_logo_npb.png": require("./ball_logo_npb.png"),
  "ball_logo_nwl.png": require("./ball_logo_nwl.png"),
  "ball_logo_pl.png": require("./ball_logo_pl.png"),
  "ball_logo_sal.png": require("./ball_logo_sal.png"),
  "ball_logo_sl.png": require("./ball_logo_sl.png"),
  "ball_logo_tl.png": require("./ball_logo_tl.png"),
  "ball_logo_cbl.png": require("./ball_logo_cbl.png"),
  "placeholder.png": require("./placeholder.png")
};

